name: DaggerCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.AEG_REGISTRY_TOKEN }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.5
    - name: Go Version
      run: |
        go version
    # - name: Install dependencies
    #   run: |
    #     go version
    #     go get -u golang.org/x/lint/golint
    - name: Run dagger CI
      run: go run ci/main.go 

    # - name: Build and Push Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true # Will only build if this is not here
    #     tags: |
    #       ghcr.io/${{ github.repository }}:latest